name: CI

on:
  push: {}
  pull_request: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup OCaml
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-version: '5.1.0'

    - name: Install Dependencies
      run: |
        opam pin add -n .
        opam depext -i -y --with-doc --with-test
        
    - name: Build
      run: opam exec -- dune build @all
      
    - name: Lint
      run: opam exec -- ocamlformat --check *.ml *.mli

    - name: Test
      run: opam exec -- dune test
